name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        IMAGE_NAME=meilisearch-mcp
        IMAGE_TAG=${GITHUB_REF#refs/tags/}
        if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
          docker build . --file Dockerfile --tag $IMAGE_NAME:latest
        elif [[ "$GITHUB_REF" == refs/tags/v* ]]; then
          docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
        fi