# .github/workflows/tagpr.yml

name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ secrets.GH_TOKEN }}
    - uses: Songmu/tagpr@35daec35e8e317247ca73d3e5620bf074a53fbd5b39e66b0 # v1.5.1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
